CREATE TABLE IF NOT EXISTS AUTH_RATE_LIMIT (
    bucket CHAR(64) NOT NULL PRIMARY KEY,
    attempts INT UNSIGNED NOT NULL DEFAULT 1,
    expiresAt BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
