<?php require_once dirname(__DIR__,3).'/header.php'; ?>
<main class="legal-page"><p class="eyebrow dark">Vos données</p><h1>Confidentialité et RGPD</h1>
<p>Cette page décrit les traitements réalisés par la médiathèque.</p>
<h2>Responsable et contact</h2><p>Le responsable du site est Mehdi Afankous. Pour toute question ou demande concernant vos données : <a href="mailto:afankous.mehdi.pro@gmail.com">afankous.mehdi.pro@gmail.com</a>. Le site est hébergé chez Hostinger.</p>
<h2>Données collectées et finalités</h2><p>Lors de l’inscription, le site enregistre votre nom, votre prénom, votre adresse e-mail et une empreinte de votre mot de passe. Ces informations servent à créer et sécuriser votre compte. Vos favoris sont associés à votre compte pour retrouver les albums que vous appréciez. Ces traitements sont nécessaires à la fourniture du service demandé. Les administrateurs disposent également d’un indicateur de rôle permettant de gérer la collection.</p>
<h2>Accès et conservation</h2><p>Les administrateurs habilités ont accès aux informations nécessaires à la gestion des comptes. L’hébergeur assure le stockage technique. Les données du compte et les favoris sont conservés tant que le compte existe ; leur suppression peut être demandée au contact indiqué ci-dessus. Les journaux techniques et sauvegardes de l’hébergement peuvent suivre un cycle de conservation distinct, à préciser par l’éditeur avant la mise en production.</p>
<h2>Vos droits</h2><p>Vous pouvez demander l’accès, la rectification ou l’effacement de vos données, ainsi que la limitation du traitement et la portabilité lorsque ces droits s’appliquent, en écrivant à l’adresse de contact. Vous pouvez également adresser une réclamation à la <a href="https://www.cnil.fr/fr/plaintes">CNIL</a>.</p>
<h2>Protection contre les abus</h2><p>Pour limiter les inscriptions automatisées et les tentatives de connexion répétées, une empreinte de l’adresse IP associée à une fenêtre de 15 minutes et un compteur sont temporairement enregistrés. Les compteurs expirés sont supprimés lors des tentatives suivantes. Cette mesure sert à protéger le service contre les abus.</p><h2>Cookies</h2><p>Le cookie de session assure la connexion et la protection des formulaires. Le cookie <code>mediatheque_consent</code> conserve votre choix pendant 180 jours. Aucun outil publicitaire ou de mesure d’audience n’est actuellement intégré. Le refus des cookies facultatifs ne bloque pas le catalogue ni la création de compte. Vous pouvez revoir votre choix à tout moment via <a href="<?= h(BASE_URL.'/index.php?cookies=1') ?>">Gérer mes cookies</a>.</p>
<p>Les cookies strictement nécessaires ne demandent pas de consentement préalable. Consultez les <a href="https://www.cnil.fr/fr/cookies-et-autres-traceurs/regles/cookies/comment-mettre-mon-site-web-en-conformite">explications de la CNIL sur les cookies</a>.</p>
<h2>Ressources externes</h2><p>Les polices Google Fonts et les fichiers Bootstrap servis par jsDelivr entraînent des connexions à ces fournisseurs, qui peuvent recevoir des informations techniques comme l’adresse IP. Les lieux de traitement et garanties applicables à l’hébergement et à ces fournisseurs doivent être confirmés par l’éditeur avant publication.</p>
</main><?php require ROOT.'/footer.php'; ?>
